version: '3.8'
services:
  book-system-db:
    image: postgres:13
    ports: 
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest      